CREATE TABLE IF NOT EXISTS users (
  user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username TEXT NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  tools TEXT NOT NULL,
  start_date TIMESTAMP DEFAULT now(),
  github TEXT,
  logged BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS projects (
  project_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  tools TEXT NOT NULL,
  phase phase NOT NULL,
  status status NOT NULL,
  start_date TIMESTAMP DEFAULT now(),
  owner INTEGER REFERENCES users(user_id) ON DELETE CASCADE,
  collaboration BOOLEAN DEFAULT TRUE,
  github TEXT
);

CREATE TABLE IF NOT EXISTS issues (
  issue_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  project_id INTEGER REFERENCES projects(project_id) ON DELETE CASCADE,
  tools TEXT NOT NULL,
  phase phase NOT NULL,
  status status NOT NULL,
  start_date TIMESTAMP DEFAULT now(),
  owner INTEGER REFERENCES users(user_id) ON DELETE CASCADE,
  collaboration BOOLEAN DEFAULT TRUE,
  github TEXT
);

CREATE TABLE IF NOT EXISTS project_collaborators (
  project_id INTEGER REFERENCES projects(project_id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(user_id) ON DELETE CASCADE
);